export const songs = [
  {
    title: 'confess',
    artist: 'Dee MC',
    artwork: require('../assets/artwork/confess.jpeg'),
    url: require('../assets/songs/confess.mp3'),
    id: 0,
    duration: 188,
  },
  {
    title: 'Arambol',
    artist: 'Dino James',
    artwork: require('../assets/artwork/arambol.jpeg'),
    url: require('../assets/songs/arambol.mp3'),
    id: 1,
    duration: 193,
  },
  {
    title: 'BadNaseeb',
    artist: 'Dee MC',
    artwork: require('../assets/artwork/naseeb.jpeg'),
    url: require('../assets/songs/badnaseeb.mp3'),
    id: 2,
    duration: 148,
  },
  {
    title: 'Jumla',
    artist: 'Dee MC',
    artwork: require('../assets/artwork/jumla.jpeg'),
    url: require('../assets/songs/jumla.mp3'),
    id: 3,
    duration: 217,
  },
  {
    title: 'confess',
    artist: 'Dee MC',
    artwork: require('../assets/artwork/confess.jpeg'),
    url: require('../assets/songs/confess.mp3'),
    id: 4,
    duration: 188,
  },
  // {
  //   title: 'Arambol',
  //   artist: 'Dino James',
  //   artwork: require('../assets/artwork/arambol.jpeg'),
  //   url: require('../assets/songs/arambol.mp3'),
  //   id: 5,
  //   duration: 193,
  // },
  // {
  //   title: 'BadNaseeb',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/naseeb.jpeg'),
  //   url: require('../assets/songs/badnaseeb.mp3'),
  //   id: 6,
  //   duration: 148,
  // },
  // {
  //   title: 'Jumla',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/jumla.jpeg'),
  //   url: require('../assets/songs/jumla.mp3'),
  //   id: 7,
  //   duration: 217,
  // },
  // {
  //   title: 'confess',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/confess.jpeg'),
  //   url: require('../assets/songs/confess.mp3'),
  //   id: 8,
  //   duration: 188,
  // },
  // {
  //   title: 'Arambol',
  //   artist: 'Dino James',
  //   artwork: require('../assets/artwork/arambol.jpeg'),
  //   url: require('../assets/songs/arambol.mp3'),
  //   id: 9,
  //   duration: 193,
  // },
  // {
  //   title: 'BadNaseeb',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/naseeb.jpeg'),
  //   url: require('../assets/songs/badnaseeb.mp3'),
  //   id: 10,
  //   duration: 148,
  // },
  // {
  //   title: 'Jumla',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/jumla.jpeg'),
  //   url: require('../assets/songs/jumla.mp3'),
  //   id: 11,
  //   duration: 217,
  // },
  // {
  //   title: 'confess',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/confess.jpeg'),
  //   url: require('../assets/songs/confess.mp3'),
  //   id: 12,
  //   duration: 188,
  // },
  // {
  //   title: 'Arambol',
  //   artist: 'Dino James',
  //   artwork: require('../assets/artwork/arambol.jpeg'),
  //   url: require('../assets/songs/arambol.mp3'),
  //   id: 13,
  //   duration: 193,
  // },
  // {
  //   title: 'BadNaseeb',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/naseeb.jpeg'),
  //   url: require('../assets/songs/badnaseeb.mp3'),
  //   id: 14,
  //   duration: 148,
  // },
  // {
  //   title: 'Jumla',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/jumla.jpeg'),
  //   url: require('../assets/songs/jumla.mp3'),
  //   id: 15,
  //   duration: 217,
  // },
  // {
  //   title: 'confess',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/confess.jpeg'),
  //   url: require('../assets/songs/confess.mp3'),
  //   id: 16,
  //   duration: 188,
  // },
  // {
  //   title: 'Arambol',
  //   artist: 'Dino James',
  //   artwork: require('../assets/artwork/arambol.jpeg'),
  //   url: require('../assets/songs/arambol.mp3'),
  //   id: 17,
  //   duration: 193,
  // },
  // {
  //   title: 'BadNaseeb',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/naseeb.jpeg'),
  //   url: require('../assets/songs/badnaseeb.mp3'),
  //   id: 18,
  //   duration: 148,
  // },
  // {
  //   title: 'Jumla',
  //   artist: 'Dee MC',
  //   artwork: require('../assets/artwork/jumla.jpeg'),
  //   url: require('../assets/songs/jumla.mp3'),
  //   id: 19,
  //   duration: 217,
  // },
];
